name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
      
    - name: Publish WebSite
      run: dotnet publish Mirehub/Mirehub.csproj -c Release -o release --nologo

    - name: Publish API
      run: dotnet publish Mirehub.Api/Mirehub.Api.csproj -c Release -o release --nologo
      
    - name: Upload Build Artifact Website
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact_WebSite
        path: /Users/Administrator/actions-runner-2/_work/Mirehub/Mirehub/release/
                
    - name: Upload Build Artifact API
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact_API
        path: /Users/Administrator/actions-runner-2/_work/Mirehub.Api/Mirehub.Api/release/

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'PRD'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
            name: Application_Artifact_WebSite
      - name: Install IIS from powershell
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: >-
            ls
            dir
          
